[package]
name = "umt_pyo3"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "umt_pyo3"
crate-type = ["cdylib"]

[dependencies]
umt_rust = "0.2.1"
pyo3 = "0.28.0"
