name: Main Package CI (Node.js)

on:
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
    setup:
        name: Setup Dependencies
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
                node-version: [20.x, 22.x, 24.x]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # 6.1.0
              with:
                node-version: ${{ matrix.node-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Install Dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i
            - name: Save Dependencies Cache
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
    test:
        name: Run Tests (Node.js)
        needs: setup
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            node-version: [20.x, 22.x, 24.x]
            bun-version: [latest]
            os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # 6.1.0
              with:
                node-version: ${{ matrix.node-version }}
            - name: Restore Dependencies Cache
              uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Run Tests with Coverage
              run: npm run test --coverage
