name: Main Package CI (Benchmark)

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      runBenchmarkName:
        type: choice
        required: true
        options:
          - chunk
          - sort

jobs:
    setup:
        name: Setup Dependencies
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Install Dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i
            - name: Save Dependencies Cache
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
    benchmark:
        name: Run Benchmark
        needs: setup
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Run Benchmark ${{ github.event.inputs.runBenchmarkName }}
              run: bun run ./src/tests/benchmark/${{ github.event.inputs.runBenchmarkName }}.ts
