name: Main Package CI (Node.js)

on:
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
      - '.github/workflows/main-package-node.yml'
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
    setup:
        name: Setup Dependencies
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
                node-version: [20.x, 22.x, 24.x]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
              with:
                node-version: ${{ matrix.node-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Install Dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i
            - name: Save Dependencies Cache
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
    test:
        name: Run Tests (Node.js)
        needs: setup
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            node-version: [20.x, 22.x, 24.x]
            bun-version: [latest]
            os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
              with:
                node-version: ${{ matrix.node-version }}
            - name: Restore Dependencies Cache
              uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Run Tests with Coverage
              run: npm run test --coverage
