name: Main Package CI (Benchmark)

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      runBenchmarkName:
        type: choice
        required: true
        options:
          - chunk
          - sort

jobs:
    setup:
        name: Setup Dependencies
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Install Dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i
            - name: Save Dependencies Cache
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
    benchmark:
        name: Run Benchmark
        needs: setup
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [latest]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Setup Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Restore Dependencies Cache
              id: cache-restore-dev-depends
              uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-bun${{ matrix.bun-version }}-${{ hashFiles('package/main/package.json') }}
            - name: Run Benchmark ${{ github.event.inputs.runBenchmarkName }}
              run: bun run ./src/tests/benchmark/${{ github.event.inputs.runBenchmarkName }}.ts
